"""Runtime renderers: convert registry skills into target Agent native formats.

Each renderer takes a LoadPlan's allowed skills and produces native files
that the target Agent can discover and consume on startup.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from agentmesh.services.registry_service import list_registry_skills
from agentmesh.utils.frontmatter import read_skill_document


@dataclass(frozen=True)
class FilePayload:
    """A file to be written by the bootstrap process."""

    path: Path
    content: str
    overwrite: bool
    description: str


class RuntimeRenderer(ABC):
    """Base class for runtime-specific skill renderers."""

    target: str

    @abstractmethod
    def render(
        self,
        home: Path,
        allowed_skills: list[str],
        metadata: dict,
    ) -> list[FilePayload]:
        """Render allowed skills into native files for the target Agent.

        Args:
            home: AgentMesh home directory.
            allowed_skills: Names of skills that passed policy gate.
            metadata: LoadPlan metadata (plan_id, generated_at, target, registry).

        Returns:
            List of FilePayload to write.
        """

    @abstractmethod
    def entrypoint_path(self, loader_dir: Path) -> Path:
        """Return the primary file path for this renderer."""


def _read_skill_content(home: Path, skill_name: str) -> str:
    """Read the SKILL.md body content for a registry skill."""
    for skill_dir in list_registry_skills(home):
        if skill_dir.name == skill_name:
            entrypoint = skill_dir / "SKILL.md"
            if entrypoint.exists():
                try:
                    doc = read_skill_document(entrypoint)
                    return doc.body if doc else entrypoint.read_text(encoding="utf-8")
                except Exception:
                    return entrypoint.read_text(encoding="utf-8")
    return ""


def _render_header(metadata: dict, allowed: int, blocked: int) -> str:
    return (
        f"# AgentMesh Auto-Loaded Skills\n"
        f"\n"
        f"> Generated by AgentMesh at {metadata.get('generated_at', 'unknown')}\n"
        f"> Plan ID: {metadata.get('plan_id', 'unknown')}\n"
        f"> Target: {metadata.get('target', 'unknown')}\n"
        f"> Allowed: {allowed} skills | Blocked: {blocked} skills\n"
        f"\n"
    )


def _render_footer(target: str) -> str:
    return (
        f"\n---\n"
        f"\n"
        f"*Managed by AgentMesh Runtime Auto-Load. Do not edit manually.*\n"
        f"*Use `agentmesh runtime disable --target {target}` to remove.*\n"
    )


class SkillMarkdownRenderer(RuntimeRenderer):
    """Render skills as a merged SKILL.md for Hermes/OpenClaw."""

    target: str = "hermes"

    def render(
        self,
        home: Path,
        allowed_skills: list[str],
        metadata: dict,
    ) -> list[FilePayload]:
        parts = [_render_header(metadata, len(allowed_skills), metadata.get("blocked", 0))]
        for name in sorted(allowed_skills):
            content = _read_skill_content(home, name)
            if content.strip():
                parts.append(f"## {name}\n\n{content}\n")
            else:
                parts.append(f"## {name}\n\n*(No content available)*\n")
            parts.append("\n---\n\n")
        parts.append(_render_footer(metadata.get("target", self.target)))

        loader_dir = metadata.get("loader_dir")
        if loader_dir:
            path = Path(loader_dir) / "SKILL.md"
        else:
            path = Path("SKILL.md")

        return [
            FilePayload(
                path=path,
                content="".join(parts),
                overwrite=True,
                description=f"Merged SKILL.md with {len(allowed_skills)} skills",
            )
        ]

    def entrypoint_path(self, loader_dir: Path) -> Path:
        return loader_dir / "SKILL.md"


class OpenClawRenderer(SkillMarkdownRenderer):
    """OpenClaw uses the same SKILL.md format as Hermes."""

    target = "openclaw"


class CursorRenderer(RuntimeRenderer):
    """Render skills as a Cursor .mdc rule file."""

    target = "cursor"

    def render(
        self,
        home: Path,
        allowed_skills: list[str],
        metadata: dict,
    ) -> list[FilePayload]:
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        frontmatter = (
            "---\n"
            f'description: "AgentMesh auto-loaded skills ({len(allowed_skills)} rules)"\n'
            "alwaysApply: true\n"
            "---\n\n"
        )
        body_parts = ["# AgentMesh Skills\n\n"]
        body_parts.append(
            f"*Loaded at {timestamp} | Plan: {metadata.get('plan_id', 'unknown')}*\n\n"
        )
        for name in sorted(allowed_skills):
            content = _read_skill_content(home, name)
            if content.strip():
                body_parts.append(f"## {name}\n\n{content}\n\n")
            else:
                body_parts.append(f"## {name}\n\n*(No content)*\n\n")

        rules_dir = metadata.get("rules_dir")
        if rules_dir:
            path = Path(rules_dir) / "agentmesh-rules.mdc"
        else:
            path = Path("agentmesh-rules.mdc")

        return [
            FilePayload(
                path=path,
                content=frontmatter + "".join(body_parts),
                overwrite=True,
                description=f"Cursor .mdc rule file with {len(allowed_skills)} skills",
            )
        ]

    def entrypoint_path(self, loader_dir: Path) -> Path:
        return loader_dir.parent / "agentmesh-rules.mdc"


class WindsurfRenderer(RuntimeRenderer):
    """Render skills as a Windsurf rules markdown file."""

    target = "windsurf"

    def render(
        self,
        home: Path,
        allowed_skills: list[str],
        metadata: dict,
    ) -> list[FilePayload]:
        parts = [_render_header(metadata, len(allowed_skills), metadata.get("blocked", 0))]
        for name in sorted(allowed_skills):
            content = _read_skill_content(home, name)
            if content.strip():
                parts.append(f"## {name}\n\n{content}\n\n")
            else:
                parts.append(f"## {name}\n\n*(No content)*\n\n")

        rules_dir = metadata.get("rules_dir")
        if rules_dir:
            path = Path(rules_dir) / "agentmesh-rules.md"
        else:
            path = Path("agentmesh-rules.md")

        return [
            FilePayload(
                path=path,
                content="".join(parts),
                overwrite=True,
                description=f"Windsurf rules file with {len(allowed_skills)} skills",
            )
        ]

    def entrypoint_path(self, loader_dir: Path) -> Path:
        return loader_dir.parent / "agentmesh-rules.md"


class AiderRenderer(RuntimeRenderer):
    """Render skills as an Aider conventions file."""

    target = "aider"

    def render(
        self,
        home: Path,
        allowed_skills: list[str],
        metadata: dict,
    ) -> list[FilePayload]:
        parts = [_render_header(metadata, len(allowed_skills), metadata.get("blocked", 0))]
        for name in sorted(allowed_skills):
            content = _read_skill_content(home, name)
            if content.strip():
                parts.append(f"## {name}\n\n{content}\n\n")

        conventions_path = metadata.get("conventions_path")
        if conventions_path:
            path = Path(conventions_path)
        else:
            path = Path.home() / ".aider.conventions.md"

        return [
            FilePayload(
                path=path,
                content="".join(parts),
                overwrite=True,
                description=f"Aider conventions with {len(allowed_skills)} skills",
            )
        ]

    def entrypoint_path(self, loader_dir: Path) -> Path:
        return Path.home() / ".aider.conventions.md"


# Renderer registry
RENDERERS: dict[str, type[RuntimeRenderer]] = {
    "hermes": SkillMarkdownRenderer,
    "openclaw": OpenClawRenderer,
    "cursor": CursorRenderer,
    "windsurf": WindsurfRenderer,
    "aider": AiderRenderer,
}


def get_renderer(target: str) -> RuntimeRenderer | None:
    """Get the appropriate renderer for a target Agent."""
    cls = RENDERERS.get(target)
    return cls() if cls else None
